-- MySQL Script generated by MySQL Workbench
-- Thu Jul 29 21:19:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dataWarehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dataWarehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataWarehouse` DEFAULT CHARACTER SET utf8 ;
USE `dataWarehouse` ;

-- -----------------------------------------------------
-- Table `dataWarehouse`.`regiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`regiones` (
  `idRegion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRegion`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataWarehouse`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`paises` (
  `idPais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idRegion` INT NOT NULL,
  PRIMARY KEY (`idPais`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_paises_regiones_idx` (`idRegion` ASC) VISIBLE,
  CONSTRAINT `fk_paises_regiones`
    FOREIGN KEY (`idRegion`)
    REFERENCES `dataWarehouse`.`regiones` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataWarehouse`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`ciudades` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_ciudades_paises1_idx` (`idPais` ASC) VISIBLE,
  CONSTRAINT `fk_ciudades_paises1`
    FOREIGN KEY (`idPais`)
    REFERENCES `dataWarehouse`.`paises` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataWarehouse`.`companias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`companias` (
  `idCompania` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `idCiudad` INT NOT NULL,
  PRIMARY KEY (`idCompania`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_companias_ciudades1_idx` (`idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_companias_ciudades1`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `dataWarehouse`.`ciudades` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataWarehouse`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`contactos` (
  `idContacto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `interes` INT NULL DEFAULT 0,
  `idCompania` INT NOT NULL,
  `idCiudad` INT NOT NULL,
  PRIMARY KEY (`idContacto`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_contactos_companias1_idx` (`idCompania` ASC) VISIBLE,
  INDEX `fk_contactos_ciudades1_idx` (`idCiudad` ASC) VISIBLE,
  CONSTRAINT `fk_contactos_companias1`
    FOREIGN KEY (`idCompania`)
    REFERENCES `dataWarehouse`.`companias` (`idCompania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  CONSTRAINT `fk_contactos_ciudades1`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `dataWarehouse`.`ciudades` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataWarehouse`.`rolesUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`rolesUsuario` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataWarehouse`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_rolesUsuario1_idx` (`idRol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_rolesUsuario1`
    FOREIGN KEY (`idRol`)
    REFERENCES `dataWarehouse`.`rolesUsuario` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataWarehouse`.`redesContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataWarehouse`.`redesContacto` (
  `idRedContacto` INT NOT NULL AUTO_INCREMENT,
  `canal` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NULL,
  `telefono` VARCHAR(45) NULL,
  `preferencia` VARCHAR(45) NOT NULL,
  `idContacto` INT NOT NULL,
  PRIMARY KEY (`idRedContacto`),
  INDEX `fk_redesContacto_contactos1_idx` (`idContacto` ASC) VISIBLE,
  CONSTRAINT `fk_redesContacto_contactos1`
    FOREIGN KEY (`idContacto`)
    REFERENCES `dataWarehouse`.`contactos` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Se inserta el rol admin y basico
-- -----------------------------------------------------
insert into rolesusuario (nombre) values ('admin'),('basico');
